# docker run --name mysql-0 -e MYSQL_ROOT_PASSWORD=12345 -p 3306:3306 -d mysql
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=12345
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080